FROM maven:3.9.10-eclipse-temurin-21
WORKDIR /workload

RUN apt-get update; \
    apt-get install -y --no-install-recommends python-is-python3 \
    && apt-get clean
 
COPY pom.xml .
COPY src ./src 
COPY dataset ./dataset

RUN mvn clean package

RUN cp target/tailored-bench-1.0.0.jar app.jar
COPY run_workload.sh /run_workload.sh
RUN chmod +x /run_workload.sh

VOLUME ["/results"]

ENTRYPOINT ["/run_workload.sh"]
